//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Collections.Generic;
    
    public partial class RentalEntities : DbContext
    {
        public RentalEntities()
            : base("name=RentalEntities")
        {}
        //public RentalEntities(string serverName)
        //    : base("Data Source=" + serverName + "; Integrated Security=true; Initial Catalog=car_rental")
        //{ }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Rental> Rentals { get; set; }
    }
}
